CREATE USER disy26_api WITH PASSWORD 'disy26_api_pw';
CREATE SCHEMA IF NOT EXISTS api AUTHORIZATION disy26_api;
GRANT ALL PRIVILEGES ON DATABASE disy26 TO disy26_api;
GRANT ALL ON SCHEMA api TO disy26_api;
ALTER SCHEMA api OWNER TO disy26_api;