name: DISY26BWI
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: api:latest
    ports:
      - "8080:8080"
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - messaging-network
      - database-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  energy-consumer:
    build:
      context: .
      dockerfile: ./energy-consumer/Dockerfile
    image: energy-consumer:latest
    depends_on:
      - rabbitmq
    networks:
      - messaging-network
    env_file:
      - .env
    restart: unless-stopped

  energy-producer:
    build:
      context: .
      dockerfile: ./energy-producer/Dockerfile
    image: energy-producer:latest
    depends_on:
      - rabbitmq
    networks:
      - messaging-network
    env_file:
      - .env
    restart: unless-stopped

  energy-update:
    build:
      context: .
      dockerfile: ./energy-update/Dockerfile
    image: energy-update:latest
    depends_on:
      - rabbitmq
      - database
    networks:
      - messaging-network
      - database-network
    env_file:
      - .env
    restart: unless-stopped

  energy-usage:
    build:
      context: .
      dockerfile: ./energy-usage/Dockerfile
    image: energy-usage:latest
    depends_on:
      - rabbitmq
      - database
    networks:
      - messaging-network
      - database-network
    env_file:
      - .env
    restart: unless-stopped

  database:
    image: "postgres:18.3"
    ports:
      - "15432:5432"
    env_file:
      - .env
    networks:
      - database-network
    volumes:
      - database-data:/var/lib/postgresql/
      - ./init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "15433:80"
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - database-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - messaging-network
    env_file:
      - .env

networks:
  database-network:
    driver: bridge

  messaging-network:
    driver: bridge

volumes:
  pgadmin-data:
  database-data:
