name: DISY26GO
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: api:latest
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  database:
    image: "postgres:18.3"
    ports:
      - "15432:5432"
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "15433:80"
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  postgres-network:
    driver: bridge

volumes:
  pgadmin-data:
  postgres-data:
