spring.application.name=EnergyProducer
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
weatherapi.latitude=48.23956
weatherapi.longitude=16.377493
weatherapi.timezone=UTC
weatherapi.panel-size-m2=5.0
weatherapi.efficiency=0.20